### ISSUE TITLE
Clarification of Repository Purpose and Commit Guidelines

### ISSUE THREAD

**Issue by koscinskic** [Allegheny-Computer-Science-203-S2020/cs203-S2020-markdown#1]
Team #2 was tasked with writing the guidelines for appropriate commit messages as a part of the cs203-S2020-assessment repository. Commit messages, while a fundamental part of technical documentation, have no relation to Markdown. These opposing guidelines should be resolved to avoid confusion when creating appropriate commit messages.

**Comment by cklima616** [comment]
We can remove the guidelines from the README file! @bagashvilit
