### ISSUE TITLE
Request for Guidelines on Using Bold and Italicized Text

### ISSUE THREAD

**Issue by koscinskic** [Allegheny-Computer-Science-203-S2020/cs203-S2020-markdown#2]
Various team members appear to be using modified text, but no standard for the proper usage of these modified texts have been created. Could the Markdown team establish some guidelines to enhance document readability?

**Comment by noorbuchi** [comment]
@koscinskic Can you please give examples of teams/branches using this modefied text so we can address this issue. Thanks!

**Comment by koscinskic** [comment]
Sure, if you look at the team2-project-management-with-github and team2-group-skills branches under the assessment repository, each branch has 2 examples using bold text.
