### ISSUE TITLE
Template Needed For Management

### ISSUE THREAD

**Issue by lussierc** [Allegheny-Computer-Science-203-S2020/cs203-S2020-markdown#3]
A Markdown template similar to those created for the Conduct and Assessment guides should be created for the Management repository, [which can be found here](https://github.com/Allegheny-Computer-Science-203-S2020/cs203-S2020-management).

This would help us to avoid running into issues where people are using different formatting for the Management document.

**Comment by cklima616** [comment]
Just uploaded!
